INSERT INTO Artists(Name) VALUES('Sam Smith');
INSERT INTO Artists(Name) VALUES('Maroon 5');
INSERT INTO Artists(Name) VALUES('Big K.R.I.T.');
INSERT INTO Artists(Name) VALUES('Kelly Clarkson');

INSERT INTO Albums(ArtistID, ReleaseDate, Title) VALUES(1,'20171103 12:00:00 AM','The Thrill of It All');
INSERT INTO Albums(ArtistID, ReleaseDate, Title) VALUES(2,'20171103 12:00:00 AM','Red Pill Blues');
INSERT INTO Albums(ArtistID, ReleaseDate, Title) VALUES(3,'20171027 12:00:00 AM','4eva is a Mighty Long Time');
INSERT INTO Albums(ArtistID, ReleaseDate, Title) VALUES(4,'20171027 12:00:00 AM','Meaning of Life');
INSERT INTO Albums(ArtistID, ReleaseDate, Title) VALUES(3,'20141110 12:00:00 AM','Cadillactica');

INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Too Good at Goodbyes',1);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Say It First',2);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'One Last Song',3);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Midnight Train',4);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Burning',5);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Him',6);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Baby, You Make Me Cry',7);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'No Peace',8);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Palace',9);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(1,'Pray',10);

INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Best 4 You',1);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'What Lovers Do',2);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Wait',3);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Lips on You',4);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Bet My Heart',5);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Help Me Out',6);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Who I Am',7);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Whiskey',8);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Girls Like You',9);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(2,'Closure',10);

INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Big K.R.I.T.',1);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Confetti',2);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Big Bank',3);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Subenstein (My Sub IV)',4);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'1999',5);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Ride Wit Me',6);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Get Up 2 Come Down',7);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Layup',8);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Classic (Interlude)',9);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Aux Cord',10);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Get Away',11);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Justin Scott',12);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Mixed Messages',13);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Keep the devil Off',14);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Miss Georgia Fornia',15);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Everlasting',16);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Higher Calling',17);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Weekend (Interlude)',18);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Price of Fame',19);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Drinking Sessions',20);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'The Light',21);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(3,'Bury Me in Gold',22);

INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'A Minute (Intro)',1);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Love So Soft',2);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Heat',3);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Meaning of Life',4);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Move You',5);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Whole Lotta Woman',6);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Medicine',7);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Cruel',8);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Didn''t I',9);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Would You Call That Love',10);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'I Don''t Think About You',11);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Slow Dance',12);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Don''t You Pretend',13);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(4,'Go High',14);

INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Kreation (Intro)',1);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Life',2);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'My Sub, Pt. 3 (Big Bang)',3);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Cadillactica',4);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Soul Food',5);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Pay Attention',6);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'King of the South',7);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Mind Control',8);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Standby (Interlude)',9);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Do You Love Me',10);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Third Eye',11);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Mo Better Cool',12);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Angels',13);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Saturdays = Celebration',14);
INSERT INTO Songs(AlbumID, Title, TrackNumber) VALUES(5,'Lost Generation',15);